import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { FileDown } from 'lucide-react'
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts'
import { useRef } from 'react'
import html2canvas from 'html2canvas'

const MONTHS = [
  'January', 'February', 'March', 'April',
  'May', 'June', 'July', 'August',
  'September', 'October', 'November', 'December'
]

const COLORS = ['#6366f1', '#22d3ee', '#22c55e', '#f59e0b', '#ef4444', '#a855f7', '#ec4899', '#14b8a6']

const ExportPDF = ({ expenses, summary, selectedMonth, selectedYear, userName }) => {
  const chartRef = useRef(null)

  const handleExport = async () => {
    const doc = new jsPDF()

    // Header background
    doc.setFillColor(99, 102, 241)
    doc.rect(0, 0, 210, 40, 'F')

    // Title
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('SpendSmart', 14, 18)

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('Expense Report', 14, 28)

    doc.setFontSize(10)
    doc.text(`${MONTHS[selectedMonth - 1]} ${selectedYear}`, 150, 18)
    doc.text(`Generated for: ${userName}`, 150, 28)

    // Summary section
    doc.setTextColor(30, 41, 59)
    doc.setFillColor(241, 245, 249)
    doc.rect(14, 48, 182, 30, 'F')

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(99, 102, 241)
    doc.text('SUMMARY', 20, 58)

    doc.setTextColor(30, 41, 59)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`Total Spent: BDT ${summary.total?.toFixed(2) || '0.00'}`, 20, 68)
    doc.text(`Total Expenses: ${summary.count || 0}`, 90, 68)
    doc.text(
      `Average: BDT ${summary.count ? (summary.total / summary.count).toFixed(2) : '0.00'}`,
      150,
      68
    )

    // Capture chart as image
    if (chartRef.current) {
      const canvas = await html2canvas(chartRef.current, { backgroundColor: '#ffffff' })
      const chartImage = canvas.toDataURL('image/png')
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(99, 102, 241)
      doc.text('SPENDING BY CATEGORY', 14, 88)
      doc.addImage(chartImage, 'PNG', 14, 92, 182, 80)
    }

    // Expenses table
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(99, 102, 241)
    doc.text('EXPENSES', 14, 182)

    autoTable(doc, {
      startY: 186,
      head: [['#', 'Title', 'Category', 'Amount (BDT)', 'Date', 'Note']],
      body: expenses.map((expense, index) => [
        index + 1,
        expense.title,
        expense.category,
        expense.amount.toFixed(2),
        new Date(expense.date).toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric',
        }),
        expense.note || '-',
      ]),
      headStyles: {
        fillColor: [99, 102, 241],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [30, 41, 59],
      },
      alternateRowStyles: {
        fillColor: [241, 245, 249],
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 45 },
        2: { cellWidth: 30 },
        3: { cellWidth: 30 },
        4: { cellWidth: 30 },
        5: { cellWidth: 37 },
      },
    })

    // Category breakdown
    const finalY = doc.lastAutoTable.finalY + 10

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(99, 102, 241)
    doc.text('CATEGORY BREAKDOWN', 14, finalY)

    const categoryData = Object.entries(summary.byCategory || {}).map(
      ([category, amount]) => [
        category,
        `BDT ${amount.toFixed(2)}`,
        `${((amount / summary.total) * 100).toFixed(1)}%`,
      ]
    )

    autoTable(doc, {
      startY: finalY + 4,
      head: [['Category', 'Amount (BDT)', 'Percentage']],
      body: categoryData,
      headStyles: {
        fillColor: [99, 102, 241],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [30, 41, 59],
      },
      alternateRowStyles: {
        fillColor: [241, 245, 249],
      },
    })

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(148, 163, 184)
      doc.text(
        `Generated by SpendSmart — Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      )
    }

    doc.save(`SpendSmart_${MONTHS[selectedMonth - 1]}_${selectedYear}.pdf`)
  }

  const chartData = Object.entries(summary.byCategory || {}).map(([name, value]) => ({
    name,
    value: parseFloat(value.toFixed(2)),
  }))

  return (
    <>
      {/* Hidden chart for PDF capture */}
      <div
        ref={chartRef}
        style={{
          position: 'absolute',
          left: '-9999px',
          background: '#ffffff',
          padding: '10px',
          width: '600px',
          height: '250px',
          display: 'flex',
          gap: '10px',
        }}
      >
        <div style={{ width: '50%', height: '100%' }}>
          <p style={{ color: '#1e293b', fontWeight: 'bold', marginBottom: '4px', fontSize: '12px' }}>Pie Chart</p>
          <ResponsiveContainer width="100%" height="90%">
            <PieChart>
              <Pie data={chartData} cx="50%" cy="50%" outerRadius={90} dataKey="value">
                {chartData.map((entry, index) => (
                  <Cell key={index} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </div>
        <div style={{ width: '50%', height: '100%' }}>
          <p style={{ color: '#1e293b', fontWeight: 'bold', marginBottom: '4px', fontSize: '12px' }}>Bar Chart</p>
          <ResponsiveContainer width="100%" height="90%">
            <BarChart data={chartData}>
              <XAxis dataKey="name" tick={{ fontSize: 10 }} />
              <YAxis tick={{ fontSize: 10 }} />
              <Tooltip />
              <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                {chartData.map((entry, index) => (
                  <Cell key={index} fill={COLORS[index % COLORS.length]} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <button onClick={handleExport} style={styles.btn}>
        <FileDown size={16} />
        Export PDF
      </button>
    </>
  )
}

const styles = {
  btn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 20px',
    background: 'linear-gradient(135deg, #22c55e, #16a34a)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 4px 15px rgba(34,197,94,0.3)',
  },
}

export default ExportPDF